// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PianoLearningTracker.DAL;

#nullable disable

namespace PianoLearningTracker.Migrations
{
    [DbContext(typeof(PianoLearningTrackerDbContext))]
    partial class PianoLearningTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "f4b865db-2f4b-4a58-848f-034748ac80f5",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "role-teacher",
                            ConcurrencyStamp = "6c9c1a97-1317-493a-95e3-f9a63f41ea80",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "role-student",
                            ConcurrencyStamp = "2185bcdc-f3ae-4fe4-9bdb-ed36ba3d2fcc",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PianoLearningTracker.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("HomeworkAssigned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 45,
                            HomeworkAssigned = "Vježbati taktove 1-20 svaki dan po 15 minuta.",
                            Notes = "Luka je dobro svladao prve dvije stranice Für Elise.",
                            ScheduledDate = new DateTime(2025, 3, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 60,
                            HomeworkAssigned = "Fokusirati se na desnu ruku, pp dinamiku u središnjem dijelu.",
                            Notes = "Petra radi na rubatu i dinamičkim nijansama Nocturna.",
                            ScheduledDate = new DateTime(2025, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 30,
                            HomeworkAssigned = "Svirati ljestvicu C-dur obje ruke, 5 minuta dnevno.",
                            Notes = "Tomislav uči pravilno držanje ruku i poziciju za Minuet.",
                            ScheduledDate = new DateTime(2025, 3, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 3,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            DurationMinutes = 45,
                            HomeworkAssigned = "",
                            Notes = "",
                            ScheduledDate = new DateTime(2025, 3, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            StudentId = 1,
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("PianoLearningTracker.Models.LessonPiece", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("PieceId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId", "PieceId");

                    b.HasIndex("PieceId");

                    b.ToTable("LessonPieces");

                    b.HasData(
                        new
                        {
                            LessonId = 1,
                            PieceId = 1,
                            Notes = "Obrađeni uvodnim taktovi."
                        },
                        new
                        {
                            LessonId = 2,
                            PieceId = 2,
                            Notes = "Rad na dinamici cijele skladbe."
                        },
                        new
                        {
                            LessonId = 3,
                            PieceId = 3,
                            Notes = "Usvajanje prvih 8 taktova."
                        });
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Composer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearComposed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pieces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Composer = "Ludwig van Beethoven",
                            Description = "Jedna od najpoznatijih klavirskih minijatura, izvrsna za učenike srednje razine.",
                            Difficulty = 1,
                            DurationMinutes = 3,
                            Genre = "Klasika",
                            Title = "Für Elise",
                            YearComposed = 1810
                        },
                        new
                        {
                            Id = 2,
                            Composer = "Frédéric Chopin",
                            Description = "Lirska skladba koja zahtijeva izražajnu dinamiku i kontrolu tona.",
                            Difficulty = 3,
                            DurationMinutes = 5,
                            Genre = "Romantizam",
                            Title = "Nocturne Op. 9 No. 2",
                            YearComposed = 1832
                        },
                        new
                        {
                            Id = 3,
                            Composer = "Johann Sebastian Bach",
                            Description = "Idealna skladba za početnike, jasna melodijska linija i jednostavan ritam.",
                            Difficulty = 0,
                            DurationMinutes = 2,
                            Genre = "Barok",
                            Title = "Minuet in G Major",
                            YearComposed = 1725
                        });
                });

            modelBuilder.Entity("PianoLearningTracker.Models.PracticeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Goals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceId")
                        .HasColumnType("int");

                    b.Property<int>("QualityRating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PieceId");

                    b.HasIndex("StudentId");

                    b.ToTable("PracticeSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 3, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 20,
                            Goals = "Svladati lijevu ruku taktova 1-20.",
                            Notes = "Fokus na lijevoj ruci, taktovi 1-10.",
                            PieceId = 1,
                            QualityRating = 4,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 3, 13, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 30,
                            Goals = "Postići kontinuitet bez zaustavljanja.",
                            Notes = "Radila cijelu skladbu sporim tempom.",
                            PieceId = 2,
                            QualityRating = 5,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 3, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 15,
                            Goals = "Zapamtiti noty prvih 8 taktova napamet.",
                            Notes = "Vježbao ljestvice i prvih 8 taktova Minueta.",
                            PieceId = 3,
                            QualityRating = 3,
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2012, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "luka.babic@email.com",
                            EnrollmentDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Luka",
                            Grade = 3,
                            LastName = "Babić",
                            Notes = "Brzo napreduje, posebno zainteresiran za klasiku.",
                            PhoneNumber = "098-123-4567",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2010, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petra.novak@email.com",
                            EnrollmentDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Petra",
                            Grade = 5,
                            LastName = "Novak",
                            Notes = "Odlična tehnika, radi na izražajnosti i dinamici.",
                            PhoneNumber = "099-234-5678",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2015, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tomislav.juric@email.com",
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tomislav",
                            Grade = 1,
                            LastName = "Jurić",
                            Notes = "Početnik, još usvaja osnove notnog čitanja.",
                            PhoneNumber = "091-345-6789",
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("PianoLearningTracker.Models.StudentPiece", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("PieceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgressRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "PieceId");

                    b.HasIndex("PieceId");

                    b.ToTable("StudentPieces");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            PieceId = 1,
                            IsCompleted = false,
                            Notes = "Svladao prvu stranicu, radi na drugoj.",
                            ProgressRating = 6,
                            StartDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 2,
                            PieceId = 2,
                            IsCompleted = false,
                            Notes = "Tehnički dobro, dorađuje izražajnost.",
                            ProgressRating = 8,
                            StartDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 2,
                            PieceId = 1,
                            CompletionDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Notes = "Završeno, izvedeno na godišnjem koncertu.",
                            ProgressRating = 10,
                            StartDate = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 3,
                            PieceId = 3,
                            IsCompleted = false,
                            Notes = "Početak rada na skladbi.",
                            ProgressRating = 3,
                            StartDate = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Diplomirala na Muzičkoj akademiji u Zagrebu, specijalist za Bacha i Chopina.",
                            Email = "marija.horvat@glazbena.hr",
                            FirstName = "Marija",
                            HireDate = new DateTime(2015, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Horvat",
                            PhoneNumber = "091-111-2233",
                            Specialization = "Klasična glazba",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Aktivni jazz glazbenik i pedagog s iskustvom u radu s učenicima svih uzrasta.",
                            Email = "ivan.kovac@glazbena.hr",
                            FirstName = "Ivan",
                            HireDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kovač",
                            PhoneNumber = "092-444-5566",
                            Specialization = "Jazz i improvizacija",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Magistrica glazbene pedagogije, fokus na suvremenim tehnikama sviranja.",
                            Email = "ana.petric@glazbena.hr",
                            FirstName = "Ana",
                            HireDate = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Petrić",
                            PhoneNumber = "095-777-8899",
                            Specialization = "Suvremena glazba",
                            YearsOfExperience = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PianoLearningTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PianoLearningTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PianoLearningTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PianoLearningTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PianoLearningTracker.Models.ApplicationUser", b =>
                {
                    b.HasOne("PianoLearningTracker.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.HasOne("PianoLearningTracker.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Lesson", b =>
                {
                    b.HasOne("PianoLearningTracker.Models.Student", "Student")
                        .WithMany("Lessons")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PianoLearningTracker.Models.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PianoLearningTracker.Models.LessonPiece", b =>
                {
                    b.HasOne("PianoLearningTracker.Models.Lesson", "Lesson")
                        .WithMany("LessonPieces")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PianoLearningTracker.Models.Piece", "Piece")
                        .WithMany("LessonPieces")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("PianoLearningTracker.Models.PracticeSession", b =>
                {
                    b.HasOne("PianoLearningTracker.Models.Piece", "Piece")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PianoLearningTracker.Models.Student", "Student")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Student", b =>
                {
                    b.HasOne("PianoLearningTracker.Models.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PianoLearningTracker.Models.StudentPiece", b =>
                {
                    b.HasOne("PianoLearningTracker.Models.Piece", "Piece")
                        .WithMany("StudentPieces")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PianoLearningTracker.Models.Student", "Student")
                        .WithMany("StudentPieces")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Lesson", b =>
                {
                    b.Navigation("LessonPieces");
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Piece", b =>
                {
                    b.Navigation("LessonPieces");

                    b.Navigation("PracticeSessions");

                    b.Navigation("StudentPieces");
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Student", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("PracticeSessions");

                    b.Navigation("StudentPieces");
                });

            modelBuilder.Entity("PianoLearningTracker.Models.Teacher", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
